
DROP TABLE IF EXISTS public.temp_purposerollup;
CREATE TABLE public.temp_purposerollup(
	DisclosureID int NOT NULL,
	API varchar(30) NULL,
	JobStartDate Timestamp(0) NULL,
	JobEndDate Timestamp(0) NULL,
	AliasedDrillingOperator varchar(255) NULL,
	FracOperator varchar(55) NULL,
	StateName varchar(100) NOT NULL,
	CountryName varchar(100) NOT NULL,
	PlayName varchar(100) NULL,
	WellName varchar(64) NOT NULL,
	TotalBaseWaterVolume (GAL) numeric(18, 2) NULL,
	Acid (LBS) decimal(38, 4) NULL,
	Antifreeze (LBS) decimal(38, 4) NULL,
	Anti-Sludge Additive (LBS) decimal(38, 4) NULL,
	Base Carrier (LBS) decimal(38, 4) NULL,
	Biocide (LBS) decimal(38, 4) NULL,
	Breaker (LBS) decimal(38, 4) NULL,
	Buffer (LBS) decimal(38, 4) NULL,
	Clay Control (LBS) decimal(38, 4) NULL,
	CNF (LBS) decimal(38, 4) NULL,
	Corrosion Inhibitor (LBS) decimal(38, 4) NULL,
	Crosslinker (LBS) decimal(38, 4) NULL,
	Defoamer (LBS) decimal(38, 4) NULL,
	Flow Enhancer (LBS) decimal(38, 4) NULL,
	Flow-Back Additive (LBS) decimal(38, 4) NULL,
	Fluid Diverter (LBS) decimal(38, 4) NULL,
	Fluid Loss Additive (LBS) decimal(38, 4) NULL,
	Foaming Agent (LBS) decimal(38, 4) NULL,
	Friction Reducer (LBS) decimal(38, 4) NULL,
	Gelling Agent (LBS) decimal(38, 4) NULL,
	Iron Control (LBS) decimal(38, 4) NULL,
	Non-Emulsifier (LBS) decimal(38, 4) NULL,
	Parafin Inhibitor (LBS) decimal(38, 4) NULL,
	Proppant (LBS) decimal(38, 4) NULL,
	Resin Activator (LBS) decimal(38, 4) NULL,
	Scale Inhibitor (LBS) decimal(38, 4) NULL,
	Solvent (LBS) decimal(38, 4) NULL,
	Stabilizer (LBS) decimal(38, 4) NULL,
	Surfactant (LBS) decimal(38, 4) NULL,
	Unknown (LBS) decimal(38, 4) NULL
	);
commit;
SET client_encoding = 'ISO_8859_5';